services:
  - type: web
    name: trading-bot
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential libta-lib0 libta-lib0-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn tradingbot_project.wsgi
