# Generated by Django 5.1.6 on 2025-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_autotradesettings_tradelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradesettings',
            name='strategy',
            field=models.CharField(choices=[('RSI', 'RSI Strategie'), ('MA_Crossover', 'Moving Average Crossover'), ('Bollinger', 'Bollinger Bands')], default='RSI', max_length=20),
        ),
    ]
