# Generated by Django 5.1.6 on 2025-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_autotradesettings_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='action',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
