# Generated by Django 5.1.6 on 2025-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_tradelog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradesettings',
            name='rsi_buy_threshold',
            field=models.IntegerField(default=30, verbose_name='RSI Koopdrempel'),
        ),
        migrations.AddField(
            model_name='autotradesettings',
            name='rsi_sell_threshold',
            field=models.IntegerField(default=70, verbose_name='RSI Verkoopdrempel'),
        ),
    ]
