# Generated by Django 5.1.6 on 2025-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_autotradesettings_rsi_buy_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradesettings',
            name='sma_long_period',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='autotradesettings',
            name='sma_short_period',
            field=models.IntegerField(default=50),
        ),
    ]
