# Generated by Django 5.1.6 on 2025-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_autotradesettings_sma_long_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradesettings',
            name='buy_margin',
            field=models.FloatField(default=0.0, verbose_name='Buy Margin'),
        ),
        migrations.AddField(
            model_name='autotradesettings',
            name='sell_margin',
            field=models.FloatField(default=0.0, verbose_name='Sell Margin'),
        ),
    ]
